sudo: required #is required to use docker service in travis

language: java

env:
  - APP_NAME=message-collector
  - AWS_ECR_ACCOUNT=09500000

jdk:
  - openjdk11

branches:
  only:
    - release/*
    - develop
    - sandbox

services:
  - docker

# clean 후 Build (Build시 자동으로 test 수행)
script:
  - gradle clean build

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

after_success:
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --no-include-email --region ap-northeast-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker build -t $APP_NAME:$TRAVIS_BUILD_ID .
  - docker tag $APP_NAME:$TRAVIS_BUILD_ID 593352196761.dkr.ecr.ap-northeast-2.amazonaws.com/$APP_NAME:$TRAVIS_BUILD_ID
  - docker push 593352196761.dkr.ecr.ap-northeast-2.amazonaws.com/$APP_NAME:$TRAVIS_BUILD_ID