language: java

env:
  - APP_NAME=message-collector

jdk:
  - openjdk11

branches:
  only:
    - release/*
    - develop
    - sandbox

services:
  - mongodb

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean 후 Build (Build시 자동으로 test 수행)
script:
  - ./gradlew clean build
