apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: webtoon-eks-demo #cluster name
  region: ap-northeast-2 #desired region

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3 #desired node count / capacity
    ssh:
      allow: false # if true - will use ~/.ssh/id_rsa.pub as the default ssh key
      #publicKeyPath:
