apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: webtoon-collector
    app.kubernetes.io/instance: webtoon-collector-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: webtoon-collector
spec:
  selector:
    app: webtoon-collector
  type: LoadBalancer
  ports:
    -  protocol: TCP
       port: 80
       targetPort: 8080